### PR TITLE
Fix error when trying to install on macOS 12.0 (Monterrey) or later

### PR DESCRIPTION
**Pull request by tfmart**
### What's in this pull request?

This pull request fixes an error when attempting to install Gryphon on a Mac running macOS 12.0 (Monterrey) or later. This issue happened because the SourceKitten dependency [increased their target version to macOS 12.0](https://github.com/jpsim/SourceKitten/releases/tag/0.33.0), while the Gryphon project itself has remained with macOS 10.13. 

Since the `Package.swift` was configured to use the latest version up to the next major, upon running the `install` script, Gryphon tried to install the latest version of the dependency, which would fail because of the target version conflict. In order to fix this, I've set the Package file to use the exact last compatible version of SourceKitten

### Does this resolve an open issue?
Yes, it resolves the issue at #118 

### Checklist for submitting a pull request:

- [x] Your code builds without any errors or warnings (warnings when running `prepareForBootstrapTests.sh` are OK).
- [x] You ran the unit tests and Bootstrapping tests for your platform.
  - [ ] If you changed any `.kt` files in the `Test cases` folder, you also ran the Acceptance tests.
- [ ] You have added new tests that check your changes (if possible).
- [x] This pull request is targeting the `development` branch (if you're contributing code) or the `gh-pages` branch (if you're contributing to the website).

### CODE REVIEW

**Review by pgneri — APPROVED** [review]

**Comment by MartyCatawiki** [comment]
@vinivendra Could you merge this PR when it fixes the issue?

**Comment by pnewell** [comment]
Until they do, this will allow you to install it:

`mint install tfmart/Gryphon@swift5.7-beta`

**Comment by pjechris** [comment]
@vinivendra is there anything preventing this MR to be merged? Seems it's needed to start using Gryphon on macOS 12+.

**Comment by vinivendra** [comment]
I believe this is no longer necessary after merging #119, right? It seems to be building fine now on macOS 13.5, Xcode 14.2, Swift 5.7.2. Let me know if I'm missing something, otherwise I'll close this PR later.

**Comment by tfmart** [comment]
Indeed this is not needed anymore with #119 being merged

**Pull request closed without merging**
